apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  type: NodePort
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api