apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-api-release-api
  labels:
    helm.sh/chart: thumbnail-api
    app.kubernetes.io/name: thumbnail-api
    app.kubernetes.io/instance: thumbnail-release
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thumbnail-api
      app.kubernetes.io/instance: thumbnail-release
  template:
    metadata:
      labels:
        helm.sh/chart: thumbnail-api
        app.kubernetes.io/name: thumbnail-api
        app.kubernetes.io/instance: thumbnail-release
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "thumbnail-api:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "thumbnail-api-release-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: IMAGE_STORAGE_PATH
              value: "/app/storage"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: image-storage
              mountPath: /app/storage
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: thumbnail-api-release-storage