apiVersion: v1
kind: Service
metadata:
  name: thumbnail-api-release-redis
  labels:
    helm.sh/chart: thumbnail-api
    app.kubernetes.io/name: thumbnail-api
    app.kubernetes.io/instance: thumbnail-release
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: thumbnail-api
    app.kubernetes.io/instance: thumbnail-release