apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thumbnail-api-release-redis
  labels:
    helm.sh/chart: thumbnail-api
    app.kubernetes.io/name: thumbnail-api
    app.kubernetes.io/instance: thumbnail-release
    app.kubernetes.io/component: redis
spec:
  serviceName: thumbnail-api-release-redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thumbnail-api
      app.kubernetes.io/instance: thumbnail-release
  template:
    metadata:
      labels:
        helm.sh/chart: thumbnail-api
        app.kubernetes.io/name: thumbnail-api
        app.kubernetes.io/instance: thumbnail-release
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "redis:7-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: data
          emptyDir: {} # Using emptyDir for simplicity in demo, as persistence not critical here.