apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
          env:
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: IMAGE_STORAGE_PATH
              value: "{{ .Values.storage.mountPath }}"
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: image-storage
              mountPath: {{ .Values.storage.mountPath }}
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage