apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-api-release-worker
  labels:
    helm.sh/chart: thumbnail-api
    app.kubernetes.io/name: thumbnail-api
    app.kubernetes.io/instance: thumbnail-release
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thumbnail-api
      app.kubernetes.io/instance: thumbnail-release
  template:
    metadata:
      labels:
        helm.sh/chart: thumbnail-api
        app.kubernetes.io/name: thumbnail-api
        app.kubernetes.io/instance: thumbnail-release
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "thumbnail-worker:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "thumbnail-api-release-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: IMAGE_STORAGE_PATH
              value: "/app/storage"
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: image-storage
              mountPath: /app/storage
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: thumbnail-api-release-storage